export const EVENTS = {
  PAYMENT_RECORDED: 'PAYMENT_RECORDED',
  ACCOUNT_ASSIGNED: 'ACCOUNT_ASSIGNED',
  ACCOUNT_CREATED: 'ACCOUNT_CREATED',
  NOTE_ADDED: 'NOTE_ADDED',
  COURT_DATE_SET: 'COURT_DATE_SET',
  SUMMONS_SERVED: 'SUMMONS_SERVED',
  LEGAL_CASE_CREATED: 'LEGAL_CASE_CREATED',
  ACCOUNT_SENT_TO_LEGAL: 'ACCOUNT_SENT_TO_LEGAL',
  COURT_CHARGES_APPLIED: 'COURT_CHARGES_APPLIED',
  PROCESS_SERVER_ASSIGNED: 'PROCESS_SERVER_ASSIGNED',
  COURT_AGENT_ASSIGNED: 'COURT_AGENT_ASSIGNED',
  AFFIDAVIT_UPLOADED: 'AFFIDAVIT_UPLOADED',
} as const
