import { getPayload } from '@/payload'
import { NextResponse } from 'next/server'

// Helper: narrow status to allowed values
type AccountStatus = 'active' | 'settled' | 'paid' | 'bankruptcy' | 'legal' | 'closed'
const allowedStatuses: AccountStatus[] = [
  'active',
  'settled',
  'paid',
  'bankruptcy',
  'legal',
  'closed',
]

function toStatus(value: string): AccountStatus | undefined {
  return allowedStatuses.includes(value as AccountStatus) ? (value as AccountStatus) : undefined
}

export async function POST(request: Request) {
  const { csv, clientId } = await request.json()
  if (!csv || !clientId)
    return NextResponse.json({ message: 'Missing CSV data or client ID' }, { status: 400 })

  const payload = await getPayload()

  // Fetch client to get prefix
  let client
  try {
    client = await payload.findByID({ collection: 'clients', id: clientId })
  } catch {
    return NextResponse.json({ message: 'Client not found' }, { status: 400 })
  }

  const prefix = (client.prefix as string).toUpperCase()
  const accountNumberBase = `${prefix}#`

  const lines = csv.trim().split('\n')
  if (lines.length < 2)
    return NextResponse.json({ message: 'CSV must have header and at least one row' })

  const headers: string[] = lines[0].split(',').map((h: string) => h.trim())
  const rows = lines.slice(1)

  let created = 0
  let updated = 0
  const errors: string[] = []
  const autoCreatedAccountNumbers: string[] = []

  for (let i = 0; i < rows.length; i++) {
    const values: string[] = rows[i].split(',').map((v: string) => v.trim())
    const record: Record<string, string> = {}
    headers.forEach((h: string, j: number) => {
      record[h] = values[j] || ''
    })

    let accountNumber = record.accountNumber?.trim()
    let isAutoGenerated = false

    if (!accountNumber) {
      accountNumber = `${accountNumberBase}${(i + 1).toString().padStart(4, '0')}-${Math.random().toString(36).slice(2, 6).toUpperCase()}`
      isAutoGenerated = true
      autoCreatedAccountNumbers.push(accountNumber)
    } else if (!accountNumber.startsWith(accountNumberBase)) {
      accountNumber = accountNumberBase + accountNumber
    }

    const status = toStatus(record.status || 'active') ?? 'active'

    try {
      const existing = await payload.find({
        collection: 'accounts',
        where: { accountNumber: { equals: accountNumber } },
      })

      let accountId: string

      if (existing.docs.length > 0) {
        // Update
        accountId = existing.docs[0].id
        await payload.update({
          collection: 'accounts',
          id: accountId,
          data: {
            debtorName: record.debtorName || existing.docs[0].debtorName,
            ssn: record.ssn || existing.docs[0].ssn,
            originalBalance: parseFloat(record.originalBalance) || existing.docs[0].originalBalance,
            currentBalance: parseFloat(record.currentBalance) ?? existing.docs[0].currentBalance,
            status,
            client: clientId,
            lastContactedAt: record.lastContactDate || existing.docs[0].lastContactedAt,
            lastContactNotes: record.lastContactNotes || existing.docs[0].lastContactNotes,
          },
        })
        updated++
      } else {
        // Create
        const newAccount = await payload.create({
          collection: 'accounts',
          data: {
            accountNumber,
            debtorName: record.debtorName,
            ssn: record.ssn || undefined,
            originalBalance: parseFloat(record.originalBalance) || 0,
            currentBalance: parseFloat(record.currentBalance) || 0,
            status,
            client: clientId,
            lastContactedAt: record.lastContactDate || undefined,
            lastContactNotes: record.lastContactNotes || undefined,
          },
        })
        accountId = newAccount.id
        created++
      }

      // Add reference if provided
      if (record.referenceName && accountId) {
        // Check for existing reference (duplicate)
        const existingRefs = await payload.find({
          collection: 'debtor-references',
          where: {
            and: [
              { account: { equals: accountId } },
              { name: { equals: record.referenceName } },
              { phone: { equals: record.referencePhone || '' } },
            ],
          },
        })
        if (existingRefs.docs.length === 0) {
          await payload.create({
            collection: 'debtor-references',
            data: {
              account: accountId,
              name: record.referenceName,
              phone: record.referencePhone || undefined,
              relationship: record.referenceRelationship || undefined,
            },
          })
        }
      }
    } catch (error: any) {
      errors.push(`Row ${i + 1}: ${error.message}`)
    }
  }

  const msgParts = [
    `Import complete. Created: ${created}, Updated: ${updated}, Errors: ${errors.length}`,
  ]
  if (autoCreatedAccountNumbers.length > 0) {
    msgParts.push(
      `Auto‑generated account numbers (cannot be updated via CSV): ${autoCreatedAccountNumbers.join(', ')}`,
    )
  }

  return NextResponse.json({
    message: msgParts.join(' | '),
    errors: errors.length ? errors : undefined,
  })
}
